
project:
  type: website

website:
  title: "TheVault"
  navbar:
    left:
      - bioinformatics.qmd
      - books.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

