---
title: "Books"
format: 
  html:
    page-layout: full
---

## Scientific Books

```{r}
#| echo: false
#| warning: false

library(tidyverse)
library(DT)
library(patchwork)

sci_books <- read_csv("data/scientific_books.csv")
datatable(sci_books,
          escape = FALSE,
          rownames = FALSE)
```

## Books I read

```{r}
#| echo: false
#| warning: false

me_books <- read_csv("data/me_books.csv")
datatable(me_books,
          escape = FALSE,
          rownames = FALSE)
```

### Plots of my read books

```{r}
#| echo: false
#| warning: false
#
year_plot <- me_books %>% 
  count(Date) %>% 
  ggplot(aes(x  = Date,
           y = n)) +
  geom_col()+ 
  scale_x_continuous(limits = c(1965, 2025),
                     breaks = seq(1965, 2025, 10),
                     expand = c(0 ,0)) +
  scale_y_continuous(limits = c(0, 3),
                     breaks = seq(0, 3, 1),
                     expand = c(0 ,0)) +
  labs(x = "Published year",
       y = "Number of read books")+
  theme_bw() +
  theme(panel.grid = element_blank(),
        panel.grid.major.y = element_line(linetype = 2,
                                          linewidth = 0.3))

genre_plot <- me_books %>% 
  count(Genre) %>% 
  ggplot(aes(x = n,
             y = Genre)) +
  geom_col() +
  scale_x_continuous(limits = c(0 ,3),
                     breaks = seq(0, 3, 1),
                     expand = c(0, 0)) +
   labs(x = "Number of read books") +
  theme_bw() +
  theme(panel.grid = element_blank(),
        panel.grid.major.x = element_line(linetype = 2,
                                          linewidth = 0.3))

year_plot / genre_plot
```
